function basis(){let t=C.cam.t,d=C.cam.d,cc=Math.cos(S.pitch),p=V(t.x+d*cc*Math.cos(S.yaw),t.y+d*cc*Math.sin(S.yaw),t.z+d*Math.sin(S.pitch)),f=norm(sub(t,p)),r=norm(cross(f,V(0,0,1))),u=norm(cross(r,f));return{p,f,r,u}}
function proj(q,el){let R=el.getBoundingClientRect(),B=basis(),v=sub(q,B.p),z=dot(v,B.f);if(z<.1)return null;let F=Math.min(R.width,R.height)*C.cam.z;return{x:R.width/2+F*dot(v,B.r)/z,y:R.height/2-F*dot(v,B.u)/z}}
function line(a,b,col,dash=[]){let A=proj(a,c),B=proj(b,c);if(!A||!B)return;g.save();g.beginPath();g.moveTo(A.x,A.y);g.lineTo(B.x,B.y);g.strokeStyle=col;g.setLineDash(dash);g.stroke();g.restore()}
function poly(P,fill,stroke){let Q=P.map(x=>proj(x,c));if(Q.some(x=>!x)||Q.length<3)return;g.beginPath();g.moveTo(Q[0].x,Q[0].y);Q.slice(1).forEach(x=>g.lineTo(x.x,x.y));g.closePath();if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}}
function cone(){let s=src(),a=norm(sub(aim(),s)),he=Math.abs(a.z)<.9?V(0,0,1):V(1,0,0),u=norm(cross(a,he)),v=norm(cross(u,a)),th=beamHalfRad(),sp=proj(s,c),gain=Math.min(powerGain(),12);if(!sp)return;let edge=[];for(let k=0;k<16;k++){let A=k*Math.PI/8,d=norm(add(mul(a,Math.cos(th)),mul(add(mul(u,Math.cos(A)),mul(v,Math.sin(A))),Math.sin(th)))),e=sceneHit(s,d,-1,false);edge.push(e?e.p:add(s,mul(d,70)))}let rings=[.28,.55,.82,1].map(f=>edge.map(e=>add(s,mul(sub(e,s),f))));g.save();g.globalCompositeOperation='screen';for(let ri=rings.length-1;ri>=0;ri--){let P=rings[ri].map(x=>proj(x,c)).filter(Boolean);if(P.length<3)continue;let al=[.065,.05,.037,.025][ri]*(.72+Math.min(gain,6)*.045);for(let k=0;k<P.length;k++){let p=P[k],q=P[(k+1)%P.length];g.beginPath();g.moveTo(sp.x,sp.y);g.lineTo(p.x,p.y);g.lineTo(q.x,q.y);g.closePath();g.fillStyle=`rgba(255,228,145,${al})`;g.fill()}g.beginPath();g.moveTo(P[0].x,P[0].y);P.slice(1).forEach(q=>g.lineTo(q.x,q.y));g.closePath();g.strokeStyle=`rgba(255,238,190,${.04+.025*(3-ri)})`;g.stroke()}let ap=proj(aim(),c);if(ap){g.beginPath();g.moveTo(sp.x,sp.y);g.lineTo(ap.x,ap.y);g.lineWidth=1.6+Math.min(2,gain*.25);g.strokeStyle='rgba(255,240,196,.38)';g.shadowColor='rgba(255,220,110,.85)';g.shadowBlur=8+Math.min(14,gain);g.stroke();g.shadowBlur=0;g.lineWidth=1;g.strokeStyle='rgba(255,252,235,.68)';g.stroke()}g.restore()}
function footprint(B){if(!B||B.P.length<3)return;let Q=B.P.map(x=>proj(x,c));if(Q.some(x=>!x))return;let xs=Q.map(x=>x.x),ys=Q.map(x=>x.y),x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys),cx=(x0+x1)/2,cy=(y0+y1)/2,rad=Math.max(14,Math.hypot(x1-x0,y1-y0)*.65),a=cl(.10+.84*tonePower(B.power),.08,.94),gr=g.createLinearGradient(x0,y0,x1,y1),gl=g.createRadialGradient(cx,cy,0,cx,cy,rad);gr.addColorStop(0,'rgba(255,255,255,.015)');gr.addColorStop(.34,B.color);gr.addColorStop(.78,B.color);gr.addColorStop(1,'rgba(255,255,255,.01)');gl.addColorStop(0,B.color);gl.addColorStop(.58,B.color);gl.addColorStop(1,'rgba(255,255,255,0)');g.save();g.beginPath();g.moveTo(Q[0].x,Q[0].y);Q.slice(1).forEach(x=>g.lineTo(x.x,x.y));g.closePath();g.globalAlpha=a*.38;g.shadowColor=B.color;g.shadowBlur=18;g.fillStyle=B.color;g.fill();g.shadowBlur=0;g.globalAlpha=a*.82;g.fillStyle=gr;g.fill();g.clip();g.globalAlpha=a*.46;g.fillStyle=gl;g.fillRect(cx-rad,cy-rad,2*rad,2*rad);g.restore()}
function render3(){let R=c.getBoundingClientRect();g.clearRect(0,0,R.width,R.height);let bg=g.createRadialGradient(R.width*.5,R.height*.46,20,R.width*.5,R.height*.46,Math.max(R.width,R.height)*.75);bg.addColorStop(0,'#1a2637');bg.addColorStop(1,'#090d13');g.fillStyle=bg;g.fillRect(0,0,R.width,R.height);poly([V(-12,-12,0),V(32,-12,0),V(32,32,0),V(-12,32,0)],'rgba(40,42,47,.96)','rgba(90,92,98,.28)');poly([V(0,0,0),V(20,0,0),V(20,20,0),V(0,20,0)],'rgba(190,190,184,.98)','rgba(236,236,228,.98)');cone();if(S.debug){for(let i=0;i<=20;i+=2){line(V(i,0,0),V(i,20,0),'#00000012');line(V(0,i,0),V(20,i,0),'#00000012')}}let sets=traces(),lit=0,eventCount=0,groupCount=0;sets.forEach((A,i)=>{if(A.length)lit++;let G=groups(A);groupCount+=G.length;for(let b of G){eventCount+=1;footprint(b);if(S.debug&&b.rep)line(b.rep.origin,b.rep.p,b.color,b.key.includes(':T')?[5,6]:[])}poly(corners(C.pieces[i]),'rgba(212,244,255,.10)','rgba(238,250,255,.90)')});let q=proj(src(),c);if(q){let rg=g.createRadialGradient(q.x,q.y,1,q.x,q.y,16);rg.addColorStop(0,'#fffbd0');rg.addColorStop(1,'rgba(255,224,112,0)');g.fillStyle=rg;g.beginPath();g.arc(q.x,q.y,16,0,7);g.fill()}st.textContent=S.debug?`${lit}/3 plaques • ${sets.reduce((z,a)=>z+a.length,0)} échantillons • ${groupCount} chemins • angle faisceau = diamètre complet • gain ×${powerGain().toFixed(1)}`:`${lit}/3 plaques • carré blanc sans épaisseur sur le sol • exposition visuelle séparée • orbite ${S.ang.toFixed(0)}° • puissance ×${powerGain().toFixed(1)}`}
function mp(p,R,b){let k=Math.min((R.width-40)/(b.maxX-b.minX),(R.height-40)/(b.maxY-b.minY));return{x:20+(p.x-b.minX)*k,y:R.height-20-(p.y-b.minY)*k}}
function render2(){let R=m.getBoundingClientRect(),sets=traces(),P=[V(0,0,0),V(20,20,0)];for(let A of sets)for(let B of groups(A))for(let p of B.P)P.push(p);let xs=P.map(x=>x.x),ys=P.map(x=>x.y),b={minX:Math.min(...xs)-3,maxX:Math.max(...xs)+3,minY:Math.min(...ys)-3,maxY:Math.max(...ys)+3};h.clearRect(0,0,R.width,R.height);h.fillStyle='#292b30';h.fillRect(0,0,R.width,R.height);let A=mp(V(0,0,0),R,b),B=mp(V(20,20,0),R,b);h.fillStyle='#bebeb8';h.fillRect(A.x,B.y,B.x-A.x,A.y-B.y);h.strokeStyle='#c9c9c2';h.strokeRect(A.x,B.y,B.x-A.x,A.y-B.y);for(let set of sets)for(let G of groups(set)){if(G.P.length<3)continue;let Q=G.P.map(p=>mp(p,R,b));h.save();h.beginPath();h.moveTo(Q[0].x,Q[0].y);Q.slice(1).forEach(p=>h.lineTo(p.x,p.y));h.closePath();h.globalAlpha=cl(.10+.84*tonePower(G.power),.08,.94);h.fillStyle=G.color;h.shadowColor=G.color;h.shadowBlur=12;h.fill();h.restore()}}
let raf=0,autoRaf=0,autoStart=0,autoBase=-180;function render(){raf=0;S.view==3?render3():render2()}function rr(){if(!raf)raf=requestAnimationFrame(render)}function autoTick(t){if(!S.auto){autoRaf=0;return}if(!autoStart)autoStart=t;let d=(t-autoStart)/5000*360,a=autoBase+d;S.ang=((a+180)%360+360)%360-180;let e=document.querySelector('#ang'),v=document.querySelector('#angv');e.value=S.ang;v.textContent=S.ang.toFixed(0)+' °';cache.key='';rr();autoRaf=requestAnimationFrame(autoTick)}
function size(){[c,m].forEach(el=>{let R=el.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.round(R.width*d),hh=Math.round(R.height*d);if(el.width!==w||el.height!==hh){el.width=w;el.height=hh;el.getContext('2d').setTransform(d,0,0,d,0,0)}});rr()}
[['ang','ang','°'],['rad','rad','cm'],['z','z','cm'],['f','beam','°']].forEach(([id,k,u])=>{let e=document.querySelector('#'+id),v=document.querySelector('#'+id+'v');function go(){S[k]=+e.value;v.textContent=e.value+' '+u;cache.key='';rr()}e.oninput=go;go()});
document.querySelector('#auto').onclick=e=>{S.auto=!S.auto;e.target.textContent=S.auto?'Rotation auto ON • 5 s':'Rotation auto OFF • 5 s';e.target.classList.toggle('on',S.auto);if(S.auto){autoBase=S.ang;autoStart=0;if(!autoRaf)autoRaf=requestAnimationFrame(autoTick)}};
document.querySelector('#sw').onclick=e=>{S.view=S.view==3?2:3;c.classList.toggle('hide',S.view!=3);m.classList.toggle('hide',S.view!=2);e.target.textContent=S.view==3?'Vue 2D':'Vue 3D';size()};document.querySelector('#dbg').onclick=e=>{S.debug=!S.debug;e.target.textContent=S.debug?'Debug ON':'Debug OFF';e.target.classList.toggle('on',S.debug);rr()};
c.onpointerdown=e=>{S.drag=1;S.px=e.clientX;S.py=e.clientY;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!S.drag)return;S.yaw-=(e.clientX-S.px)*.008;S.pitch=cl(S.pitch+(e.clientY-S.py)*.008,.15,1.45);S.px=e.clientX;S.py=e.clientY;rr()};c.onpointerup=c.onpointercancel=()=>S.drag=0;
new ResizeObserver(size).observe(document.querySelector('main'));addEventListener('resize',size);addEventListener('pageshow',()=>setTimeout(size,60));requestAnimationFrame(size);setTimeout(size,300);setTimeout(size,900);